name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
        cache: true

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: "pnpm"

         # Add this step before installing dependencies
    - name: Clean Install
      run: |
        pnpm store prune
        rm -rf node_modules pnpm-lock.yaml
        pnpm install
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Lint
      run: pnpm run lint
      
    - name: Build
      run: pnpm run build
    